### ISSUE TITLE
User redirect after signup.

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#123]
Create a page for informing the user to check their mail after the activation link is sent to their mail ID and redirect the user to that page after the signup button has been clicked.

**Comment by ShivamTyagi12345** [comment]
so Basically a page with a button to send user to their mails?

**Comment by PalakKumari** [comment]
> so basically a page with a button to send users to their emails?

No just a page informing user to check their mail.

**Comment by ShivamTyagi12345** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/60812924/152296959-83ddaf76-f421-4bc9-aa52-75b050b5884f.png">
Is it right?
