### ISSUE TITLE
Add proper error handling.

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#131]
Change the Send error function and modify the sendError response from all routes.

**Comment by ShivamTyagi12345** [comment]
What do i modify sendError function to? I have to work in these files api/
1/connection
2. /created-events
3./getevents
4. /organisation-dashboard
5. /products
6. /orgprofilecomp
7. /update??

**Comment by PalakKumari** [comment]
What is the progress of this task?

**Comment by ShivamTyagi12345** [comment]
Unexpected college works are bit of a bump. All that's left is to check 3 more routes for errors

**Comment by ShivamTyagi12345** [comment]
made the pr
