### ISSUE TITLE
Add delete products section on organisation dashboard.

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#170]
Design it in figma, get confirmed and then create it.

**Comment by KISHAN-del** [comment]
ok mam

**Comment by KISHAN-del** [comment]
![eed9e50a-5a19-4b33-85cf-c92b8d1786cb](https://user-images.githubusercontent.com/76819584/154042877-bc9326f0-81f9-443c-82fa-5f7fc8713e2b.jpg)
 mam iske alawa kya kya add karna h,,
