### ISSUE TITLE
Create Events Page

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#21]
Model the events page by taking inspiration from figma design.
Deadline: 8-Jan-2022

**Comment by Vivek3072** [comment]
> Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022

Mam it would be better if we can discuss on the figma design before I start coding the page.

**Comment by PalakKumari** [comment]
> > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> 
> Mam it would be better if we can discuss on the figma design before I start coding the page.

Okay inform me the time when you want to have the discussion, we can have a meet for that.

**Comment by Vivek3072** [comment]
> > > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> > 
> > 
> > Mam it would be better if we can discuss on the figma design before I start coding the page.
> 
> Okay inform me the time when you want to have the discussion, we can have a meet for that.

4 pm today?

**Comment by PalakKumari** [comment]
> > > > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> > > 
> > > 
> > > Mam it would be better if we can discuss on the figma design before I start coding the page.
> > 
> > 
> > Okay inform me the time when you want to have the discussion, we can have a meet for that.
> 
> 4 pm today?

Might not be available at that time. Will be available anytime post 7:00 pm.

**Comment by Vivek3072** [comment]
> > > > > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> > > > 
> > > > 
> > > > Mam it would be better if we can discuss on the figma design before I start coding the page.
> > > 
> > > 
> > > Okay inform me the time when you want to have the discussion, we can have a meet for that.
> > 
> > 
> > 4 pm today?
> 
> Might not be available at that time. Will be available anytime post 7:00 pm.
ok mam you tell the time I'm free

**Comment by PalakKumari** [comment]
> > > > > > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> > > > > 
> > > > > 
> > > > > Mam it would be better if we can discuss on the figma design before I start coding the page.
> > > > 
> > > > 
> > > > Okay inform me the time when you want to have the discussion, we can have a meet for that.
> > > 
> > > 
> > > 4 pm today?
> > 
> > 
> > Might not be available at that time. Will be available anytime post 7:00 pm.
> > ok mam you tell the time I'm free

7:30 pm

**Comment by Vivek3072** [comment]
> > > > > > > Model the events page by taking inspiration from figma design. Deadline: 8-Jan-2022
> > > > > > 
> > > > > > 
> > > > > > Mam it would be better if we can discuss on the figma design before I start coding the page.
> > > > > 
> > > > > 
> > > > > Okay inform me the time when you want to have the discussion, we can have a meet for that.
> > > > 
> > > > 
> > > > 4 pm today?
> > > 
> > > 
> > > Might not be available at that time. Will be available anytime post 7:00 pm.
> > > ok mam you tell the time I'm free
> 
> 7:30 pm

ok mam
