### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by rishabhborn2win** [gdscnitp/Environmental-Awareness-App#3]
Take the ref. of the ER Diagram and with all the validators

**Comment by ShivamTyagi12345** [comment]
ok . can u please provide the initial hints on getting started:)

**Comment by PalakKumari** [comment]
You have to   create each schema for the fields provided in database diagram, use mongoose for creating the schema. Create each field with adequate datatype and mark required for the ones that must be provided by the user. To get a clear picture you can take help from the models of tenants app.
