### ISSUE TITLE
Add/delete products routes

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#57]
Create a route for adding/deleting products to/from the database.

**Comment by ShivamTyagi12345** [comment]
i would need few more details on the task

**Comment by ShivamTyagi12345** [comment]
@PalakKumari  Can u please provide an elaborate layout of how can I complete this issue?

**Comment by PalakKumari** [comment]
@ShivamTyagi12345 what's the status of this task? you're expected to create the PR by tomorrow.
