### ISSUE TITLE
Error handling and user redirect after login

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#58]
Implement Proper error handling and add functionality to redirect the user to their respective dashboard pages.

**Comment by ShivamTyagi12345** [comment]
i am in @SrijanShovit  <signUpWork> branch. Under Route _http://localhost:3000/login_ i login with 

- palak234@gmail.com
-  testdscTenv*$app123
But i get 

----------------------|------------------
<img width="958" alt="image" src="https://user-images.githubusercontent.com/60812924/149612189-d522ebd6-336f-45d2-a5c3-b30dacbb51b8.png"> | 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/60812924/149612211-47adc153-cbe9-4fe5-8d68-dae37ce86110.png">
-----------------|-------------

Also under _http://localhost:3000/signupin_ signing up a new individual adds no new object under <Individuals> collections

**Comment by PalakKumari** [comment]
> @PalakKumari ,I am in @SrijanShovit **signUpWork** branch. Under Route _http://localhost:3000/login_ i login with
> 
> * [palak234@gmail.com](mailto:palak234@gmail.com)
> * testdscTenv*$app123
>   But i get
> 
> ----------------------|------------------ <img alt="image" width="958" src="https://user-images.githubusercontent.com/60812924/149612189-d522ebd6-336f-45d2-a5c3-b30dacbb51b8.png"> | <img alt="image" width="424" src="https://user-images.githubusercontent.com/60812924/149612211-47adc153-cbe9-4fe5-8d68-dae37ce86110.png"> -----------------|-------------
> 
> Also under _http://localhost:3000/signupin_ signing up a new individual adds no new object under collections

This is because you haven't set up the .env file properly.

**Comment by PalakKumari** [comment]
Let's have a meet at 1:00 pm. Will help you resolve this.
