### ISSUE TITLE
create a JS Object with list of error constants and message

### ISSUE THREAD

**Issue by rishabhborn2win** [gdscnitp/Environmental-Awareness-App#6]
Create a list with all the errors so that for throwing a error directly we can fetch the code from that file and throw it to the user

**Comment by rishabhborn2win** [comment]
![WhatsApp Image 2021-11-30 at 9 57 15 AM](https://user-images.githubusercontent.com/55771529/143986659-edaf7945-7eae-453f-aef4-bc7fd618b940.jpeg)

take the ref. of the above code snippet for creating the error list object.

**Comment by ShivamTyagi12345** [comment]
okay
