### ISSUE TITLE
Implement custom logger in the application

### ISSUE THREAD

**Issue by rishabhborn2win** [gdscnitp/Environmental-Awareness-App#7]
Logger logs the error in the console with proper description which we code

https://medium.com/gradeup/how-to-implement-custom-logger-in-nextjs-a0495cbfda53

**Comment by PalakKumari** [comment]
@vian9 What is the status of your task?

**Comment by ShivamTyagi12345** [comment]
is this issue still open for work?

**Comment by PalakKumari** [comment]
Yes
