### ISSUE TITLE
Client-Side email validation in forms

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#89]
Create validation in forms to notify users if they enter wrong inputs in the form fields.

**Comment by PalakKumari** [comment]
What is the progress of this task?

**Comment by KISHAN-del** [comment]
⁩ mam wo import wagarah karwa diya h amisha ne bs function banana h n usko
use karna sign up log in page m ..kl evng m PR create kar denge mam
