### ISSUE TITLE
Add working navbar on homepage

### ISSUE THREAD

**Issue by PalakKumari** [gdscnitp/Environmental-Awareness-App#91]
add navbar on the index page with the signup pop connected to the button and after clicking the buttons on the popup user should be taken to the respective signup page. Also connect the login page.

**Comment by vian9** [comment]
I have already connected this with the Issue Connecting button.

**Comment by PalakKumari** [comment]
> I have already connected this with the Issue Connecting button.

The navbar is changed. So make changes to the home page navbar accordingly.

**Comment by PalakKumari** [comment]
Good work✨

**Comment by vian9** [comment]
> Good work✨

Thanks 🤩
